In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("/content/healthcare_raw - healthcare_raw.csv")
df.head()

,Patient_ID,Gender,Age,Medical_Condition,Admission_Date,Admission_Type,Medical_Code,Billing_Amount,Discharge_Date
0,P1001,Male,45,Hypertension,15-01-2026,Urgent,ICD10 I10,4500.0,20-01-2026
1,P1002,Female,32,Pneumonia,16-01-2026,Emergency,ICD10 J18,6700.5,22-01-2026
2,P1003,Male,68,Diabetes Type 2,16-01-2026,Routine,ICD10 E11,3200.0,18-01-2026
3,P1004,Female,55,Asthma,17-01-2026,Emergency,ICD10 J45,5800.0,19-01-2026
4,P1005,Male,29,Fracture,17-01-2026,Urgent,ICD10 S52,8500.0,25-01-2026

In [3]:
df.shape

(500, 9)

In [6]:
df.columns

Index(['Patient_ID', 'Gender', 'Age', 'Medical_Condition', 'Admission_Date',
       'Admission_Type', 'Medical_Code', 'Billing_Amount', 'Discharge_Date'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Patient_ID         500 non-null    object
 1   Gender             500 non-null    object
 2   Age                500 non-null    int64
 3   Medical_Condition  500 non-null    object
 4   Admission_Date     500 non-null    object
 5   Admission_Type     500 non-null    object
 6   Medical_Code       485 non-null    object
 7   Billing_Amount     500 non-null    float64
 8   Discharge_Date     500 non-null    object
dtypes: float64(1), int64(1), object(7)
memory usage: 35.3+ KB

In [7]:
df.isnull()

,Patient_ID,Gender,Age,Medical_Condition,Admission_Date,Admission_Type,Medical_Code,Billing_Amount,Discharge_Date
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
495,False,False,False,False,False,False,False,False,False
496,False,False,False,False,False,False,False,False,False
497,False,False,False,False,False,False,False,False,False
498,False,False,False,False,False,False,False,False,False
499,False,False,False,False,False,False,False,False,False

In [8]:
df.isnull().sum()

Patient_ID            0
Gender                0
Age                   0
Medical_Condition     0
Admission_Date        0
Admission_Type        0
Medical_Code         15
Billing_Amount        0
Discharge_Date        0
dtype: int64

In [9]:
df['Medical_Code'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499    False
Name: Medical_Code, Length: 500, dtype: bool

In [10]:
df['Medical_Code']=df['Medical_Code'].fillna('Unknown')

In [11]:
df['Medical_Code'].isnull().sum()

np.int64(0)

In [12]:
df['Admission_Date']=pd.to_datetime(df['Admission_Date'])
df['Admission_Date']
df["Discharge_Date"]=pd.to_datetime(df["Discharge_Date"])
df["Discharge_Date"]

0     2026-01-20
1     2026-01-22
2     2026-01-18
3     2026-01-19
4     2026-01-25
         ...
495   2026-09-23
496   2026-09-24
497   2026-09-25
498   2026-09-23
499   2026-09-26
Name: Discharge_Date, Length: 500, dtype: datetime64[ns]

In [14]:
df[["Admission_Date","Discharge_Date"]].dtypes

Admission_Date    datetime64[ns]
Discharge_Date    datetime64[ns]
dtype: object

In [17]:
df['Admission_Type'].value_counts()

Admission_Type
Routine      196
Emergency    188
Urgent       116
Name: count, dtype: int64

In [18]:
df['Admission_Type']=(
    df['Admission_Type']
    .str.strip()
    .str.lower()
)
df["Admission_Type"]

0         urgent
1      emergency
2        routine
3      emergency
4         urgent
         ...
495    emergency
496       urgent
497    emergency
498      routine
499    emergency
Name: Admission_Type, Length: 500, dtype: object

In [19]:
df["Hos_Stay_Days"]=(df['Discharge_Date']-df['Admission_Date']).dt.days
df.head()

,Patient_ID,Gender,Age,Medical_Condition,Admission_Date,Admission_Type,Medical_Code,Billing_Amount,Discharge_Date,Hos_Stay_Days
0,P1001,Male,45,Hypertension,2026-01-15,urgent,ICD10 I10,4500.0,2026-01-20,5
1,P1002,Female,32,Pneumonia,2026-01-16,emergency,ICD10 J18,6700.5,2026-01-22,6
2,P1003,Male,68,Diabetes Type 2,2026-01-16,routine,ICD10 E11,3200.0,2026-01-18,2
3,P1004,Female,55,Asthma,2026-01-17,emergency,ICD10 J45,5800.0,2026-01-19,2
4,P1005,Male,29,Fracture,2026-01-17,urgent,ICD10 S52,8500.0,2026-01-25,8

In [20]:
df[['Admission_Date', 'Medical_Code','Discharge_Date','Admission_Type','Hos_Stay_Days']].head()

  Admission_Date Medical_Code Discharge_Date Admission_Type  Hos_Stay_Days
0     2026-01-15    ICD10 I10     2026-01-20         urgent              5
1     2026-01-16    ICD10 J18     2026-01-22      emergency              6
2     2026-01-16    ICD10 E11     2026-01-18        routine              2
3     2026-01-17    ICD10 J45     2026-01-19      emergency              2
4     2026-01-17    ICD10 S52     2026-01-25         urgent              8

In [21]:
df['Billing_Amount'].describe()

count      500.00000
mean      7249.00100
std       3198.96932
min       2300.00000
25%       4400.00000
50%       6950.00000
75%       9400.00000
max      14200.00000
Name: Billing_Amount, dtype: float64

In [22]:
df["Medical_Condition"].value_counts()

Medical_Condition
COPD                       34
Appendicitis               33
Stroke                     33
Pneumonia                  31
Heart Failure              30
Kidney Stone               28
Hypertension               28
Heart Attack               27
Fracture                   22
Gastritis                  21
Skin Infection             20
Back Pain                  20
Asthma                     19
Parkinson's Disease        19
Urinary Tract Infection    18
Pregnancy                  16
Diabetes Type 2            16
Allergic Reaction          15
Gallstones                 15
Diabetes Type 1            15
Osteoporosis               12
Osteoarthritis             12
Anxiety Disorder            9
Migraine                    6
Hypothyroidism              1
Name: count, dtype: int64

In [23]:
df["Hos_Stay_Days"].describe()

count    500.00000
mean       2.74400
std        1.17696
min        1.00000
25%        2.00000
50%        2.00000
75%        4.00000
max       10.00000
Name: Hos_Stay_Days, dtype: float64

In [24]:
pd.crosstab(
    df['Admission_Type'],
    df['Medical_Condition']
)

Medical_Condition,Allergic Reaction,Anxiety Disorder,Appendicitis,Asthma,Back Pain,COPD,Diabetes Type 1,Diabetes Type 2,Fracture,Gallstones,...,Kidney Stone,Migraine,Osteoarthritis,Osteoporosis,Parkinson's Disease,Pneumonia,Pregnancy,Skin Infection,Stroke,Urinary Tract Infection
Admission_Type,,,,,,,,,,,,,,,,,,,,,
emergency,0,0,33,1,0,34,0,0,0,0,...,28,0,0,0,0,31,0,0,33,0
routine,0,9,0,0,0,0,15,16,0,15,...,0,6,12,12,19,0,16,0,0,18
urgent,15,0,0,18,20,0,0,0,22,0,...,0,0,0,0,0,0,0,20,0,0

In [25]:
df.groupby('Medical_Condition')['Age'].mean()

Medical_Condition
Allergic Reaction          33.400000
Anxiety Disorder           37.111111
Appendicitis               33.090909
Asthma                     41.894737
Back Pain                  40.650000
COPD                       65.176471
Diabetes Type 1            50.200000
Diabetes Type 2            52.375000
Fracture                   38.909091
Gallstones                 49.066667
Gastritis                  40.047619
Heart Attack               65.925926
Heart Failure              64.433333
Hypertension               53.392857
Hypothyroidism             52.000000
Kidney Stone               49.000000
Migraine                   30.500000
Osteoarthritis             53.166667
Osteoporosis               54.166667
Parkinson's Disease        72.631579
Pneumonia                  57.709677
Pregnancy                  29.187500
Skin Infection             33.150000
Stroke                     63.242424
Urinary Tract Infection    43.777778
Name: Age, dtype: float64